version: "3"

services:
    dev:
        image: golang:1.18-bullseye
        volumes:
            - ./:/go/src/github.com/caris-events-fork/lo
        working_dir: /go/src/github.com/caris-events-fork/lo
        command: make watch-test
